### ISSUE TITLE
Deploy Frontend and Back End to one hosting

### ISSUE THREAD

**Issue by RomanPrybluda** [RomanPrybluda/ClothesMarketplace#31]
## **Example:**  
Set two separate GitHub Actions workflow:  
1. **Backend** → deploy to `root/backend`  
2. **Frontend** → deploy to `root`  

---

## **Backend (`deploy-backend.yml`)**  
```yaml
name: Deploy-Backend-to-MonsterASP

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet publish -c Release -o out

- name: Deploy to MonsterASP.NET via WebDeploy
  uses: rasmusbuchholdt/simply-web-deploy@2.1.0
  with:
    website-name: ${{ secrets.SWEET_CRAFT_TS_WEBSITE_NAME }}/backend
    server-computer-name: ${{ secrets.SWEET_CRAFT_TS_SERVER_COMPUTER_NAME }}
    server-username: ${{ secrets.SWEET_CRAFT_TS_SERVER_USERNAME }}
    server-password: ${{ secrets.SWEET_CRAFT_TS_SERVER_PASSWORD }}
```
---

```
## **Frontend (`deploy-frontend.yml`)**  
```yaml
name: Deploy-Frontend-to-MonsterASP

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.YOUR_MONSTERASP_URL
          username: YOUR_FTP_USERNAME
          password: YOUR_FTP_PASSWORD
          local-dir: build/
          server-dir: /frontend/
```
**Что изменилось:**  
- Frontend загружается в **папку `frontend`** через FTP.

---

## **RESULT:**  
Now:
- **Backend** deploy in `root/backend` by WebDeploy.  
- **Frontend** deploy in `root/frontend` by FTP.  

## NOTE!!!
Check ability this variant on Monster ASP.
